apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: application-name
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: application-name
  minReplicas: 1
  maxReplicas: 3

  metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 50
